### ISSUE TITLE
user-friendliness

### ISSUE THREAD

**Issue by wpaetzold** [metagenomics/bioPipeline#1]
Delivery of all parameters which can be changed like cutt-offs (e-Value, score, ...) and keywords as an Input for the Pipeline.
Default values if no parameter is set.

**Comment by pbelmann** [comment]
For this issue we first have to decide how and where we can define the parameters. 
I suggest to use a [YAML](https://de.wikipedia.org/wiki/YAML) file that can be configured by the user.

**Comment by pbelmann** [comment]
Since we are using the nextflow configuration file, there is no need to use a YAML files.
In my opinion is the last step in order to close this issue, a short getting started section in the readme.
