### ISSUE TITLE
integrate the scripts into Nextfolw

### ISSUE THREAD

**Issue by wpaetzold** [metagenomics/bioPipeline#2]
Build one connected pipeline with all scripts in it. So only one call is necessary to run all scripts.

**Comment by pbelmann** [comment]
I recommend adopting Nextflow in a step by step fashion. 
The first step could be the integration of HMMSearch.sh and createFolder.sh.
I think we should split this issue in multiple ones.

**Comment by pbelmann** [comment]
all scripts are now available as a nextflow  pipeline
